### ISSUE TITLE
Add Support for Custom Textures

### ISSUE THREAD

**Issue by DrkMatr1984** [crysis992/moneydrops#1]
Newer spigot versions allow you to associate custom textures with items through their [ItemMeta](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.html#getCustomModelData--). Could you add support for this in your config? Thanks!

**Comment by crysis992** [comment]
This has now been added and can be used in the latest development build which can be found here:
https://ci.avarioncraft.de/job/MoneyDrops/

To add a model data just add a value behind the material like:

```
 '1':
    material: GOLD_NUGGET:2
    rangeMin: 1
    rangeMax: 10
  '2':
    material: GOLD_INGOT:1
    rangeMin: 10
    rangeMax: 50

```

**Comment by DrkMatr1984** [comment]
Wow! That was fast! :) I'll give it some testing and if there are any problems (Which I don't anticipate, it's pretty straightforward) I'll open a new issue. Case closed!
