### ISSUE TITLE
Merge moneydrops and minewallet

### ISSUE THREAD

**Issue by jolvary** [crysis992/moneydrops#2]
Can you merge or do something so that money drops uses the plugin minewallet as currency plugin? Ty.

![image](https://user-images.githubusercontent.com/32238907/72088174-ef41a380-3309-11ea-98ed-c8027929cc29.png)

**Comment by crysis992** [comment]
The plugin uses Vault to handle money transactions.
Make sure your economy plugin has a proper Vault integration/support and you don't have multiple economy plugins installed.

**Comment by jolvary** [comment]
Probably having essentialsx and minewallet is causing that problem, i will try to deactivate essentials as currency plugin. Tell you if something change. Ty.

**Comment by jolvary** [comment]
Mmmm not sure how to do this, could you help me a bit? My plugins are these:

- EssentialsX
- GCore
- ID-Library
- LuckPerms
- Minewallet
- MoneyDrops
- PlaceHolder API
- Plugin Constructor
- ProtocolLib
- Towny
- Vault

Sorry for being so useless.

**Comment by crysis992** [comment]
Try to use a different economy plugin. I've checked the plugin minewallet and if you read the comments on their page you'll see that many users have similar problems with different plugins that use the economy feature.
I've also checked MineWallets source code and this plugin is poorly coded, it will lag your server when using the SQL feature and it does not even support UUIDs (name changes) without data loss.

There is not much I can do if MineWallet is not using Vault correctly, that's up to the developer of this plugin to fix this issue.

You can try to get rid of this plugin and switch to one from spigot like:
https://www.spigotmc.org/resources/saneeconomy-simple-but-featureful-economy.26223/
or
https://www.spigotmc.org/resources/the-new-economy.7805/
or use the inbuild money/economy system from EssentialsX

**Comment by jolvary** [comment]
Thanks so much, I have been trying other economy plugins just in case and found MySQLEconomyBank, it seems as it uses Essentials economy so, probably I will use it. But looking at TNE it seems to be a great plugin. Thanks for everything, I really appreciate your help! 😊
